import { defineConfig } from 'astro/config';
import node from '@astrojs/node';

export default defineConfig({
  output: 'server',
  adapter: node({
    mode: 'standalone',
  }),
  redirects: {
    '/services': '/solutions/custom-software-automation/',
    '/shopify-company-store': '/solutions/shopify-company-store/',
    '/shopify-sage-connect-integration': '/solutions/shopify-sage-connect-integration/',
    '/enterprise-shopify-automation': '/solutions/enterprise-shopify-automation/',
    '/shopify-migration-service': '/solutions/custom-software-automation/',
    '/shopify-development-agency-swishtag': '/solutions/custom-software-automation/',
    '/ui-ux-design-services': '/solutions/custom-software-automation/',
    '/shopify-agency-new-york': '/solutions/custom-software-automation/',
    '/shopify-theme-development': '/solutions/custom-software-automation/',
    '/shopify-ecommerce-solutions-for-promotional-product-distributors': '/solutions/shopify-company-store/',
    '/shopify-customer-migration': '/solutions/custom-software-automation/',
    '/platform': '/platforms/',
    '/punchout-solutions': '/platforms/punchout-solutions/',
    '/promo-plus': '/platforms/promo-plus/',
    '/xecutor': '/platforms/xecutor/',
    '/shopify-apps-for-promotional-products': '/platforms/shopify-apps-for-promotional-products/',
    '/rocket-gift-card-and-discount-shopify-app': '/platforms/shopify-apps-for-promotional-products/',
    '/platform/punchout': '/platforms/punchout-solutions/',
    '/product/punchout': '/platforms/punchout-solutions/',
    '/platform/purchase-orders': '/platforms/punchout-solutions/',
    '/platform/invoices': '/platforms/punchout-solutions/',
    '/platform/multi-store': '/platforms/',
    '/platform/transactions': '/platforms/',
    '/integrations': '/platforms/',
    '/integrations/cxml': '/platforms/punchout-solutions/',
    '/integrations/jaggaer': '/platforms/punchout-solutions/',
    '/integrations/sap-ariba': '/platforms/punchout-solutions/',
    '/integrations/coupa': '/platforms/punchout-solutions/',
    '/integrations/oci': '/platforms/punchout-solutions/',
    '/integrations/oracle': '/platforms/punchout-solutions/',
    '/integrations/workday': '/platforms/punchout-solutions/',
    '/promotional-products-distributors': '/industries/promotional-products-distributors/',
    '/promotional-products-suppliers': '/industries/promotional-products-suppliers/',
    '/promotional-products-decorators': '/industries/promotional-products-decorators/',
    '/industries/promotional-print-uniforms': '/industries/promotional-products-distributors/',
    '/industries/industrial-mro': '/industries/',
    '/industries/lab-scientific': '/industries/',
    '/manufacturing-execution-system': '/platforms/xecutor/',
  },
});
